//
//  DiallingCodes.swift
//  Relays
//
//  A phone number only means something with a country in front of it. The form
//  asked for one field and hoped, which works for whoever wrote it and nobody
//  else.
//
//  The table is ISO 3166-1 codes to ITU calling codes, derived from the
//  mledoze/countries dataset. Countries whose calling code covers several
//  territories keep the shared root: the United States and Canada are both 1,
//  Russia and Kazakhstan both 7. Country names are not in here — the system
//  knows them in the reader's language, and this app has its own language
//  setting to ask with.
//

import Foundation

struct DiallingCode: Identifiable, Hashable, Sendable {
    /// ISO 3166-1 alpha-2.
    let region: String
    /// Digits, without the plus.
    let code: String

    var id: String { region }

    var name: String {
        Format.locale.localizedString(forRegionCode: region) ?? region
    }

    /// Regional indicator symbols: the two letters shifted into the flag block.
    var flag: String {
        String(String.UnicodeScalarView(region.unicodeScalars.compactMap {
            Unicode.Scalar(127_397 + $0.value)
        }))
    }

    /// What goes in front of the number.
    var prefix: String { "+" + code }

    /// The reader's own country if the table has it, otherwise the busiest one
    /// that is not a guess about them.
    static var current: DiallingCode {
        let region = Locale.current.region?.identifier
        return all.first { $0.region == region } ?? all.first { $0.region == "US" } ?? all[0]
    }

    static func named(_ region: String) -> DiallingCode? {
        all.first { $0.region == region }
    }

    /// Sorted the way they are read, in the language they are read in.
    static var sortedByName: [DiallingCode] {
        all.sorted { $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending }
    }

    static let all: [DiallingCode] = [
        DiallingCode(region: "AD", code: "376"),
        DiallingCode(region: "AE", code: "971"),
        DiallingCode(region: "AF", code: "93"),
        DiallingCode(region: "AG", code: "1268"),
        DiallingCode(region: "AI", code: "1264"),
        DiallingCode(region: "AL", code: "355"),
        DiallingCode(region: "AM", code: "374"),
        DiallingCode(region: "AO", code: "244"),
        DiallingCode(region: "AR", code: "54"),
        DiallingCode(region: "AS", code: "1684"),
        DiallingCode(region: "AT", code: "43"),
        DiallingCode(region: "AU", code: "61"),
        DiallingCode(region: "AW", code: "297"),
        DiallingCode(region: "AX", code: "35818"),
        DiallingCode(region: "AZ", code: "994"),
        DiallingCode(region: "BA", code: "387"),
        DiallingCode(region: "BB", code: "1246"),
        DiallingCode(region: "BD", code: "880"),
        DiallingCode(region: "BE", code: "32"),
        DiallingCode(region: "BF", code: "226"),
        DiallingCode(region: "BG", code: "359"),
        DiallingCode(region: "BH", code: "973"),
        DiallingCode(region: "BI", code: "257"),
        DiallingCode(region: "BJ", code: "229"),
        DiallingCode(region: "BL", code: "590"),
        DiallingCode(region: "BM", code: "1441"),
        DiallingCode(region: "BN", code: "673"),
        DiallingCode(region: "BO", code: "591"),
        DiallingCode(region: "BQ", code: "599"),
        DiallingCode(region: "BR", code: "55"),
        DiallingCode(region: "BS", code: "1242"),
        DiallingCode(region: "BT", code: "975"),
        DiallingCode(region: "BV", code: "47"),
        DiallingCode(region: "BW", code: "267"),
        DiallingCode(region: "BY", code: "375"),
        DiallingCode(region: "BZ", code: "501"),
        DiallingCode(region: "CA", code: "1"),
        DiallingCode(region: "CC", code: "61"),
        DiallingCode(region: "CD", code: "243"),
        DiallingCode(region: "CF", code: "236"),
        DiallingCode(region: "CG", code: "242"),
        DiallingCode(region: "CH", code: "41"),
        DiallingCode(region: "CI", code: "225"),
        DiallingCode(region: "CK", code: "682"),
        DiallingCode(region: "CL", code: "56"),
        DiallingCode(region: "CM", code: "237"),
        DiallingCode(region: "CN", code: "86"),
        DiallingCode(region: "CO", code: "57"),
        DiallingCode(region: "CR", code: "506"),
        DiallingCode(region: "CU", code: "53"),
        DiallingCode(region: "CV", code: "238"),
        DiallingCode(region: "CW", code: "599"),
        DiallingCode(region: "CX", code: "61"),
        DiallingCode(region: "CY", code: "357"),
        DiallingCode(region: "CZ", code: "420"),
        DiallingCode(region: "DE", code: "49"),
        DiallingCode(region: "DJ", code: "253"),
        DiallingCode(region: "DK", code: "45"),
        DiallingCode(region: "DM", code: "1767"),
        DiallingCode(region: "DO", code: "1"),
        DiallingCode(region: "DZ", code: "213"),
        DiallingCode(region: "EC", code: "593"),
        DiallingCode(region: "EE", code: "372"),
        DiallingCode(region: "EG", code: "20"),
        DiallingCode(region: "EH", code: "2"),
        DiallingCode(region: "ER", code: "291"),
        DiallingCode(region: "ES", code: "34"),
        DiallingCode(region: "ET", code: "251"),
        DiallingCode(region: "FI", code: "358"),
        DiallingCode(region: "FJ", code: "679"),
        DiallingCode(region: "FK", code: "500"),
        DiallingCode(region: "FM", code: "691"),
        DiallingCode(region: "FO", code: "298"),
        DiallingCode(region: "FR", code: "33"),
        DiallingCode(region: "GA", code: "241"),
        DiallingCode(region: "GB", code: "44"),
        DiallingCode(region: "GD", code: "1473"),
        DiallingCode(region: "GE", code: "995"),
        DiallingCode(region: "GF", code: "594"),
        DiallingCode(region: "GG", code: "44"),
        DiallingCode(region: "GH", code: "233"),
        DiallingCode(region: "GI", code: "350"),
        DiallingCode(region: "GL", code: "299"),
        DiallingCode(region: "GM", code: "220"),
        DiallingCode(region: "GN", code: "224"),
        DiallingCode(region: "GP", code: "590"),
        DiallingCode(region: "GQ", code: "240"),
        DiallingCode(region: "GR", code: "30"),
        DiallingCode(region: "GS", code: "500"),
        DiallingCode(region: "GT", code: "502"),
        DiallingCode(region: "GU", code: "1671"),
        DiallingCode(region: "GW", code: "245"),
        DiallingCode(region: "GY", code: "592"),
        DiallingCode(region: "HK", code: "852"),
        DiallingCode(region: "HN", code: "504"),
        DiallingCode(region: "HR", code: "385"),
        DiallingCode(region: "HT", code: "509"),
        DiallingCode(region: "HU", code: "36"),
        DiallingCode(region: "ID", code: "62"),
        DiallingCode(region: "IE", code: "353"),
        DiallingCode(region: "IL", code: "972"),
        DiallingCode(region: "IM", code: "44"),
        DiallingCode(region: "IN", code: "91"),
        DiallingCode(region: "IO", code: "246"),
        DiallingCode(region: "IQ", code: "964"),
        DiallingCode(region: "IR", code: "98"),
        DiallingCode(region: "IS", code: "354"),
        DiallingCode(region: "IT", code: "39"),
        DiallingCode(region: "JE", code: "44"),
        DiallingCode(region: "JM", code: "1876"),
        DiallingCode(region: "JO", code: "962"),
        DiallingCode(region: "JP", code: "81"),
        DiallingCode(region: "KE", code: "254"),
        DiallingCode(region: "KG", code: "996"),
        DiallingCode(region: "KH", code: "855"),
        DiallingCode(region: "KI", code: "686"),
        DiallingCode(region: "KM", code: "269"),
        DiallingCode(region: "KN", code: "1869"),
        DiallingCode(region: "KP", code: "850"),
        DiallingCode(region: "KR", code: "82"),
        DiallingCode(region: "KW", code: "965"),
        DiallingCode(region: "KY", code: "1345"),
        DiallingCode(region: "KZ", code: "7"),
        DiallingCode(region: "LA", code: "856"),
        DiallingCode(region: "LB", code: "961"),
        DiallingCode(region: "LC", code: "1758"),
        DiallingCode(region: "LI", code: "423"),
        DiallingCode(region: "LK", code: "94"),
        DiallingCode(region: "LR", code: "231"),
        DiallingCode(region: "LS", code: "266"),
        DiallingCode(region: "LT", code: "370"),
        DiallingCode(region: "LU", code: "352"),
        DiallingCode(region: "LV", code: "371"),
        DiallingCode(region: "LY", code: "218"),
        DiallingCode(region: "MA", code: "212"),
        DiallingCode(region: "MC", code: "377"),
        DiallingCode(region: "MD", code: "373"),
        DiallingCode(region: "ME", code: "382"),
        DiallingCode(region: "MF", code: "590"),
        DiallingCode(region: "MG", code: "261"),
        DiallingCode(region: "MH", code: "692"),
        DiallingCode(region: "MK", code: "389"),
        DiallingCode(region: "ML", code: "223"),
        DiallingCode(region: "MM", code: "95"),
        DiallingCode(region: "MN", code: "976"),
        DiallingCode(region: "MO", code: "853"),
        DiallingCode(region: "MP", code: "1670"),
        DiallingCode(region: "MQ", code: "596"),
        DiallingCode(region: "MR", code: "222"),
        DiallingCode(region: "MS", code: "1664"),
        DiallingCode(region: "MT", code: "356"),
        DiallingCode(region: "MU", code: "230"),
        DiallingCode(region: "MV", code: "960"),
        DiallingCode(region: "MW", code: "265"),
        DiallingCode(region: "MX", code: "52"),
        DiallingCode(region: "MY", code: "60"),
        DiallingCode(region: "MZ", code: "258"),
        DiallingCode(region: "NA", code: "264"),
        DiallingCode(region: "NC", code: "687"),
        DiallingCode(region: "NE", code: "227"),
        DiallingCode(region: "NF", code: "672"),
        DiallingCode(region: "NG", code: "234"),
        DiallingCode(region: "NI", code: "505"),
        DiallingCode(region: "NL", code: "31"),
        DiallingCode(region: "NO", code: "47"),
        DiallingCode(region: "NP", code: "977"),
        DiallingCode(region: "NR", code: "674"),
        DiallingCode(region: "NU", code: "683"),
        DiallingCode(region: "NZ", code: "64"),
        DiallingCode(region: "OM", code: "968"),
        DiallingCode(region: "PA", code: "507"),
        DiallingCode(region: "PE", code: "51"),
        DiallingCode(region: "PF", code: "689"),
        DiallingCode(region: "PG", code: "675"),
        DiallingCode(region: "PH", code: "63"),
        DiallingCode(region: "PK", code: "92"),
        DiallingCode(region: "PL", code: "48"),
        DiallingCode(region: "PM", code: "508"),
        DiallingCode(region: "PN", code: "64"),
        DiallingCode(region: "PR", code: "1"),
        DiallingCode(region: "PS", code: "970"),
        DiallingCode(region: "PT", code: "351"),
        DiallingCode(region: "PW", code: "680"),
        DiallingCode(region: "PY", code: "595"),
        DiallingCode(region: "QA", code: "974"),
        DiallingCode(region: "RE", code: "262"),
        DiallingCode(region: "RO", code: "40"),
        DiallingCode(region: "RS", code: "381"),
        DiallingCode(region: "RU", code: "7"),
        DiallingCode(region: "RW", code: "250"),
        DiallingCode(region: "SA", code: "966"),
        DiallingCode(region: "SB", code: "677"),
        DiallingCode(region: "SC", code: "248"),
        DiallingCode(region: "SD", code: "249"),
        DiallingCode(region: "SE", code: "46"),
        DiallingCode(region: "SG", code: "65"),
        DiallingCode(region: "SH", code: "2"),
        DiallingCode(region: "SI", code: "386"),
        DiallingCode(region: "SJ", code: "4779"),
        DiallingCode(region: "SK", code: "421"),
        DiallingCode(region: "SL", code: "232"),
        DiallingCode(region: "SM", code: "378"),
        DiallingCode(region: "SN", code: "221"),
        DiallingCode(region: "SO", code: "252"),
        DiallingCode(region: "SR", code: "597"),
        DiallingCode(region: "SS", code: "211"),
        DiallingCode(region: "ST", code: "239"),
        DiallingCode(region: "SV", code: "503"),
        DiallingCode(region: "SX", code: "1721"),
        DiallingCode(region: "SY", code: "963"),
        DiallingCode(region: "SZ", code: "268"),
        DiallingCode(region: "TC", code: "1649"),
        DiallingCode(region: "TD", code: "235"),
        DiallingCode(region: "TF", code: "262"),
        DiallingCode(region: "TG", code: "228"),
        DiallingCode(region: "TH", code: "66"),
        DiallingCode(region: "TJ", code: "992"),
        DiallingCode(region: "TK", code: "690"),
        DiallingCode(region: "TL", code: "670"),
        DiallingCode(region: "TM", code: "993"),
        DiallingCode(region: "TN", code: "216"),
        DiallingCode(region: "TO", code: "676"),
        DiallingCode(region: "TR", code: "90"),
        DiallingCode(region: "TT", code: "1868"),
        DiallingCode(region: "TV", code: "688"),
        DiallingCode(region: "TW", code: "886"),
        DiallingCode(region: "TZ", code: "255"),
        DiallingCode(region: "UA", code: "380"),
        DiallingCode(region: "UG", code: "256"),
        DiallingCode(region: "UM", code: "268"),
        DiallingCode(region: "US", code: "1"),
        DiallingCode(region: "UY", code: "598"),
        DiallingCode(region: "UZ", code: "998"),
        DiallingCode(region: "VA", code: "3"),
        DiallingCode(region: "VC", code: "1784"),
        DiallingCode(region: "VE", code: "58"),
        DiallingCode(region: "VG", code: "1284"),
        DiallingCode(region: "VI", code: "1340"),
        DiallingCode(region: "VN", code: "84"),
        DiallingCode(region: "VU", code: "678"),
        DiallingCode(region: "WF", code: "681"),
        DiallingCode(region: "WS", code: "685"),
        DiallingCode(region: "XK", code: "383"),
        DiallingCode(region: "YE", code: "967"),
        DiallingCode(region: "YT", code: "262"),
        DiallingCode(region: "ZA", code: "27"),
        DiallingCode(region: "ZM", code: "260"),
        DiallingCode(region: "ZW", code: "263"),
    ]
}
